import type { Metadata } from "next";
import { Caveat, Kalam, Bebas_Neue, Poppins } from "next/font/google";
import "./globals.css";

const kalam = Kalam({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-kalam",
});

const bebasNeue = Bebas_Neue({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bebasNeue",
});

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Medit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kalam.variable} ${bebasNeue.variable} ${poppins.variable} font-primary`}
      >
        {children}
      </body>
    </html>
  );
}
